import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0f131d",
        surface: "#0f131d",
        "surface-dim": "#0f131d",
        "surface-bright": "#353944",
        "surface-container-lowest": "#0a0e17",
        "surface-container-low": "#171c25",
        "surface-container": "#1b2029",
        "surface-container-high": "#262a34",
        "surface-container-highest": "#31353f",
        "surface-variant": "#31353f",
        "surface-tint": "#d0bcff",
        "on-surface": "#dfe2f0",
        "on-surface-variant": "#cbc3d7",
        "on-background": "#dfe2f0",
        outline: "#958ea0",
        "outline-variant": "#494454",
        primary: "#d0bcff",
        "on-primary": "#3c0091",
        "primary-container": "#a078ff",
        "on-primary-container": "#340080",
        "primary-fixed": "#e9ddff",
        "primary-fixed-dim": "#d0bcff",
        "inverse-primary": "#6d3bd7",
        secondary: "#ddb7ff",
        "on-secondary": "#490080",
        "secondary-container": "#6f00be",
        "on-secondary-container": "#d6a9ff",
        "secondary-fixed": "#f0dbff",
        "secondary-fixed-dim": "#ddb7ff",
        tertiary: "#ffb0cd",
        "on-tertiary": "#640039",
        "tertiary-container": "#f751a1",
        "on-tertiary-container": "#570032",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        "container-max": "1280px",
        "container-margin": "24px",
        "container-mobile": "20px",
      },
      boxShadow: {
        glow: "0 0 20px rgba(208, 188, 255, 0.15)",
        "glow-lg": "0 0 35px rgba(192, 132, 252, 0.35)",
        "glow-btn": "0 0 30px rgba(160, 120, 255, 0.4)",
        "nav-glow": "0 0 20px rgba(208, 188, 255, 0.1)",
        "orb-glow": "0 0 80px 20px rgba(160, 120, 255, 0.4)",
      },
      backgroundImage: {
        "aurora-gradient": "linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)",
        "btn-gradient": "linear-gradient(to right, #d0bcff, #ddb7ff)",
        "text-gradient": "linear-gradient(to right, #d0bcff, #ddb7ff, #a078ff)",
      },
      animation: {
        "pulse-glow": "pulse-glow 4s ease-in-out infinite",
        "pulse-ring": "pulse-ring 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        float: "float 6s ease-in-out infinite",
      },
      keyframes: {
        "pulse-glow": {
          "0%, 100%": { transform: "scale(1)", opacity: "0.8" },
          "50%": { transform: "scale(1.1)", opacity: "1" },
        },
        "pulse-ring": {
          "0%": { transform: "scale(0.8)", opacity: "0" },
          "50%": { opacity: "0.5" },
          "100%": { transform: "scale(1.5)", opacity: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
