[theme]
primaryColor = "#d0bcff"
backgroundColor = "#0f131d"
secondaryBackgroundColor = "#1b2029"
textColor = "#dfe2f0"
font = "sans-serif"

[ui]
hideTopBar = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
