[theme]
primaryColor = "#4cd7f6"
backgroundColor = "#0e1416"
secondaryBackgroundColor = "#1b2122"
textColor = "#dee3e6"
font = "sans-serif"

[ui]
hideTopBar = true

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
